from __future__ import annotations

DEFAULT_SKILLS = [
    "Java",
    "Python",
    "C#",
    "JavaScript",
    "TypeScript",
    "React",
    "Angular",
    "Vue",
    "HTML",
    "CSS",
    "Spring Boot",
    ".NET",
    "SQL",
    "Git",
    "Linux",
    "TestNG",
    "JUnit",
    "PyTest",
    "Selenium",
    "Playwright",
    "Cypress",
    "Appium",
    "REST Assured",
    "REST API",
    "Postman",
    "SOAP",
    "GraphQL",
    "Jenkins",
    "GitHub Actions",
    "Azure DevOps",
    "GitLab CI",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Helm",
    "LLM",
    "RAG",
    "LangChain",
    "LangGraph",
    "Prompt Engineering",
    "AI Testing",
    "Agentic AI",
    "Oracle",
    "SQL Server",
    "PostgreSQL",
    "MongoDB",
    "Jira",
    "ALM",
    "Zephyr",
    "Xray",
    "Leadership",
    "Communication",
    "Stakeholder Management",
    "Team Management",
    "Requirements Analysis",
    "Product Requirements",
    "Test Scheduling",
    "Test Strategy",
    "Validation Strategy",
    "Functional Requirements",
    "Non-Functional Requirements",
    "System Requirements",
    "PASS/FAIL Criteria",
    "Shift-Left Testing",
    "Test Implementation Strategy",
    "Software Architecture",
    "Debug Strategy",
    "Test Automation Strategy",
    "Automation Frameworks",
    "Validation Processes",
    "Validation Methodologies",
    "Product Validation",
    "Validation Plan",
    "Test Time Reduction",
    "Test Results Analysis",
    "Bin Pareto",
    "Report Generation",
    "Test Findings",
    "Document Revision Tracking",
    "Defect Management",
    "Root Cause Analysis",
    "Corrective Actions",
    "Failure Reproduction",
    "Bug Traceability",
    "Bachelor of Science",
    "Engineering",
    "Validation Experience",
    "PCIe SSD",
    "NAND",
    "Memory Storage Hierarchy",
    "NVMe Protocol",
    "Python Scripting",
    "Problem Analysis",
    "AI-Assisted Coding",
    "AI Tools",
    "Artificial Intelligence Workflows",
    "Build Efficiency",
    "Generative AI",
    "Large Language Models",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Retrieval Augmented Generation",
    "Vector Databases",
    "Vector Search",
    "Semantic Search",
    "Embeddings",
    "Evaluation Frameworks",
    "AI Agents",
    "Agentic Workflows",
    "Function Calling",
    "MCP",
    "Model Context Protocol",
    "Fine-Tuning",
    "Prompt Evaluation",
    "Responsible AI",
    "AI Governance",
    "OpenAI",
    "Azure OpenAI",
    "Anthropic",
    "Hugging Face",
    "Google Cloud",
    "Microsoft Azure",
    "Amazon Web Services",
    "Serverless",
    "Microservices",
    "Event-Driven Architecture",
    "API Gateway",
    "Service Mesh",
    "Istio",
    "Argo CD",
    "GitOps",
    "Platform Engineering",
    "Infrastructure as Code",
    "Pulumi",
    "Ansible",
    "Prometheus",
    "Grafana",
    "OpenTelemetry",
    "Observability",
    "Site Reliability Engineering",
    "Data Engineering",
    "Data Pipelines",
    "Apache Kafka",
    "Apache Spark",
    "Databricks",
    "Snowflake",
    "dbt",
    "Data Lakehouse",
    "Redis",
    "Elasticsearch",
    "BigQuery",
    "Data Governance",
    "Cybersecurity",
    "Zero Trust",
    "Identity and Access Management",
    "OAuth2",
    "OpenID Connect",
    "JWT",
    "Secrets Management",
    "Threat Modeling",
    "DevSecOps",
    "Software Supply Chain Security",
    "SAST",
    "DAST",
    "Container Security",
    "WebAssembly",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Node.js",
    "Next.js",
    "FastAPI",
    "Django",
    "Spring Cloud",
    "GraphQL Federation",
    "Webhooks",
    "Contract Testing",
    "Consumer-Driven Contracts",
    "Chaos Engineering",
    "Load Testing",
    "Performance Engineering",
    "Accessibility Testing",
    "Visual Regression Testing",
    "Playwright",
    "Cypress",
    "Testcontainers",
]


def extract_skills(text: str) -> list[str]:
    """Extract likely technology skills from a JD or resume."""
    found: list[str] = []
    lowered = text.lower()
    for skill in DEFAULT_SKILLS:
        if skill.lower() in lowered:
            found.append(skill)
    return sorted(set(found), key=lambda item: item.lower())
