[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 1

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#5143b5"
backgroundColor = "#f3f5fc"
secondaryBackgroundColor = "#eaf0ff"
textColor = "#20333f"
font = "sans serif"
